const labels = {
  labels: {
    agency: "Agency",
    stage: "Innovation Stage",
    solution: "Solution",
    sector: "Sector",
    category: "Innovation Category",
    DOT: "DOT",
    DOE: "DOE",
    USDA: "USDA",
    DOI: "DOI",
    power: "Power",
    transportation_sector: "Transportation",
    industry: "Industry",
    agriculture_sector: "Agriculture",
    buildings: "Buildings",
    forestry: "Forestry",
    efficiency: "Efficiency",
    clean_electricity: "Clean Electricity",
    electrification: "Electrification",
    fuels: "Low-Carbon Fuels",
    carbon_management: "Carbon Management",
    non_co2: "Non-CO2 Reductions",
    land_sink: "Land Sink",
    other: "Other",
    rd: "R&D",
    piloting: "Piloting & Demos",
    deployment: "Deployment",
    energy_water: "Energy & Water",
    transportation_fs: "Transportation-HUD",
    agriculture_fs: "Agriculture",
    interior_environment: "Interior & Environment",
    iija: "IIJA",
    ira: "IRA",
    approps: "Annual Appropriations",
    one_time: "One-Time Appropriations",
    funding_type: "Funding Type",
    funding_source: "Funding Source",
    annual_appropriations: "Annual Appropriations",

  },
  getLabel: function (label) {
    return this.labels[label] ? this.labels[label] : label;
  },
};

export default labels;
